version: '3.7'
services:
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    environment:
      USER_DB_HOST: "user_db"
      USER_DB_PORT: ${USER_DB_PORT}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: "postgres"
      USER_DB_NAME: "postgres"
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      USER_COMMAND_SUBJECT: ${USER_COMMAND_SUBJECT}
      USER_REPLY_SUBJECT: ${USER_REPLY_SUBJECT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    networks:
      - servers
    ports:
      - '8082:8082'
    depends_on:
      - user_db

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: always
    ports:
      - '9090:9090'
    environment:
      USER_DB_HOST: "user_db"
      USER_DB_PORT: ${USER_DB_PORT}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: "postgres"
      USER_DB_NAME: "postgres"
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      USER_COMMAND_SUBJECT: ${USER_COMMAND_SUBJECT}
      USER_REPLY_SUBJECT: ${USER_REPLY_SUBJECT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
      USER_SERVICE_HOST: "user_service"
      POST_SERVICE_HOST: "post_service"
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
    networks:
      - servers
    depends_on:
      - user_db

  post_service:
    image: post_service
    container_name: post_service
    build:
      context: .
      dockerfile: ./post_service/Dockerfile
    restart: always
    ports:
      - '8083:8083'
    environment:
      POST_DB_HOST: "post_db"
      POST_DB_PORT: "27017"
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      USER_COMMAND_SUBJECT: ${USER_COMMAND_SUBJECT}
      USER_REPLY_SUBJECT: ${USER_REPLY_SUBJECT}
    depends_on:
      - post_db
    networks:
      - servers

  message_service:
    image: message_service
    container_name: message_service
    build:
      context: .
      dockerfile: ./message_service/Dockerfile
    restart: always
    ports:
      - '8085:8085'
    environment:
      MESSAGE_DB_HOST: "message_db"
      MESSAGE_DB_PORT: "27017"
      MESSAGE_SERVICE_PORT: ${MESSAGE_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      USER_COMMAND_SUBJECT: ${USER_COMMAND_SUBJECT}
      USER_REPLY_SUBJECT: ${USER_REPLY_SUBJECT}
    depends_on:
      - message_db
    networks:
      - servers

  user_db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - servers
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '4000:5432'
    volumes:
      - user-data:/var/lib/postgresql/data

  post_db:
    image: mongo
    container_name: post_db
    restart: always
    ports:
      - '4001:27017'
    volumes:
      - posts-data:/data/db
    networks:
      - servers

  message_db:
    image: mongo
    container_name: message_db
    restart: always
    ports:
      - '4003:27017'
    volumes:
      - message_data:/data/db
    networks:
      - servers

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - servers
    ports:
      - 4222:4222

volumes:
  user-data:
    name: user-database
  posts-data:
    name: posts-database
  message_data:
    name: message-database

networks:
  servers:
    name: servers
    driver: bridge